# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="A system for distributed translation submissions"
HOMEPAGE="http://transifex.org"
SRC_URI="http://transifex.org/files/${P}.tar.gz"
LICENSE="GPL-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE="test mercurial bzr git subversion cvs notification"
DEPEND="dev-python/setuptools
	test? ( dev-python/nose )"
RDEPEND=">=dev-python/django-1.0
	dev-python/markdown
	dev-python/httplib2
	dev-python/pygments
	dev-python/python-openid
	dev-python/django-authopenid
	dev-python/django-pagination
	sys-devel/gettext
	dev-util/intltool
	>=dev-python/turbogears-1.0.4
	>=dev-python/genshi-0.4.4
	>=dev-python/sqlalchemy-0.4.6
	>=dev-python/toscawidgets-0.9.2
	>=dev-python/tw.forms-0.9.1
	>=dev-python/pygments-0.9
	>=dev-python/Babel-0.9
	mercurial? ( dev-util/mercurial )
	git? ( dev-util/git )
	bzr? ( dev-util/bzr 
		dev-util/bzrtools )
	subsversion? ( dev-util/subversion 
		dev-python/pysvn )
	cvs? ( dev-util/cvs )
	notification? ( dev-python/django-notification )"

src_test() {
	PYTHONPATH=. "${python}" setup.py nosetests || die "tests failed"
}

