--- ipheth-pair/Makefile.orig	2010-02-23 10:35:56.000000000 +0200
+++ ipheth-pair/Makefile	2010-02-23 10:37:02.099913826 +0200
@@ -1,4 +1,3 @@
-CFLAGS += -Wall -O2
 LDLIBS += -limobiledevice
 
 all: ipheth-pair
@@ -6,9 +5,8 @@
 ipheth-pair: ipheth-pair.o
 
 install:
-	install -m 0755 ipheth-pair /lib/udev/
-	install -m 0644 90-iphone-tether.rules /etc/udev/rules.d
-	/sbin/udevadm control --reload-rules
+	install -D -m 0755 ipheth-pair ${DESTDIR}/lib/udev/ipheth-pair
+	install -D -m 0644 90-iphone-tether.rules ${DESTDIR}/etc/udev/rules.d/90-iphone-tether.rules
 
 clean:
 	rm -f *.o ipheth-pair
