#!/bin/sh

GAMEDIR="/opt/tumiki-bin"
STARTDIR="tumiki"
EXE="./tf"

mkdir -p "${HOME}/.${STARTDIR}"
cd "${HOME}/.${STARTDIR}"
mkdir -p "replay"

for f in `find "${GAMEDIR}" -maxdepth 1 -mindepth 1 -printf '%f '` ; do
	[ -e "${f}" ] && continue
	ln -s "${GAMEDIR}/${f}" "${f}" >& /dev/null
done

exec "${EXE}" "$@"
