masters = gentoo guru
thin-manifests = true
sign-manifests = false
cache-formats = md5-dict
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
eapis-banned = 0 1 2 3 4 5 6
eapis-deprecated = 7
update-changelog = false
profile-formats = portage-2
