# Copyright 2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=7
inherit eutils

DESCRIPTION="A Device Firmware Update based USB programmer for Atmel chips"
HOMEPAGE="http://dfu-programmer.sourceforge.net"
SRC_URI="http://sourceforge.net/projects/dfu-programmer/files/dfu-programmer/${PV}/dfu-programmer-${PV}.tar.gz"
LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE=""

DEPEND="
	dev-libs/libusb
	sys-fs/udev"
RDEPEND="${DEPEND}"

src_prepare() {
	epatch "${FILESDIR}"/fix_as_needed.patch
}

src_install() {
	emake DESTDIR="${D}" install || die "make install failed"
	einfo "Generating UDEV rules..."
	UDEV_RULES="$(get_libdir)/udev/rules.d/70-dfu-programmer.rules"
	mkdir -p "${D}"/${UDEV_RULES%/*}
	echo -e "#\n# do not edit this file, it will be overwritten on update\n#" \
		> "${D}"/${UDEV_RULES}
	for prodid in "2ffa" "2ffb" "2ff9" "2ff7" "2ff4" "2ff3" ;
	do
		echo "SUBSYSTEM==\"usb\", ACTION==\"add\", ATTRS{idVendor}==\"03eb\", \
		ATTRS{idProduct}==\"${prodid}\", MODE=\"660\", GROUP=\"plugdev\", \
		SYMLINK+=\"dfu-%n\"" >> "${D}"${UDEV_RULES}
	done
}
