# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/pybeanstalk/pybeanstalk-0.11.1.ebuild,v 1.2 2009/07/27 07:15:16 mr_bones_ Exp $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI="2"
inherit distutils

DESCRIPTION="Python module for interaction with beanstalkd"
HOMEPAGE="http://code.google.com/p/pybeanstalk/"
SRC_URI="http://pybeanstalk.googlecode.com/files/${P}.tar.gz"
LICENSE="GPL-3"
KEYWORDS="~x86 ~amd64"
SLOT="0"
IUSE=""

RDEPEND="virtual/python"
DEPEND="${RDEPEND}
		dev-python/setuptools"

S="${WORKDIR}"/"${PV}"
