#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	use dns net
}

init_env_vars() {
	export HBASE_HOME="/opt/hbase-VERSION"

	# source hadoop-env.sh
	if test -f ${HBASE_HOME}/conf/hbase-env.sh; then
		. ${HBASE_HOME}/conf/hbase-env.sh
	fi

	# check for the required paths
	checkpath -d -m 0770 -o root:hadoop "${HBASE_PID_DIR}"
}

start() {
	ebegin "Starting HBase ${DAEMON}"
	init_env_vars
	start-stop-daemon --start --quiet \
		--pidfile ${HBASE_PID_DIR}/hbase-hbase-master.pid \
		-u hbase -x ${HBASE_HOME}/bin/hbase-daemon.sh -- \
		--config ${HBASE_CONF_DIR} start master
	eend $?
}

stop() {
	ebegin "Stopping HBase ${DAEMON}"
	init_env_vars
	start-stop-daemon --stop --quiet \
		--pidfile ${HBASE_PID_DIR}/hbase-hbase-master.pid
	eend $?
}

