# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.3

EAPI=8

CRATES="
	ahash@0.8.12
	aho-corasick@1.1.4
	ariadne@0.6.0
	borsh@1.7.0
	bumpalo@3.20.3
	bytes@1.12.0
	cc@1.2.64
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	const-random-macro@0.1.16
	const-random@0.1.18
	crunchy@0.2.4
	find-msvc-tools@0.1.9
	fnv@1.0.7
	getrandom@0.2.17
	getrandom@0.3.4
	inline_colorization@0.1.6
	js-sys@0.3.102
	lexical-core@1.0.6
	lexical-parse-float@1.0.6
	lexical-parse-integer@1.0.6
	lexical-util@1.0.7
	lexical-write-float@1.0.6
	lexical-write-integer@1.0.6
	libc@0.2.186
	libffi-sys@4.1.0
	libffi@5.1.0
	libloading@0.9.0
	libmimalloc-sys@0.1.49
	logos-codegen@0.16.1
	logos-derive@0.16.1
	logos@0.16.1
	memchr@2.8.2
	mimalloc@0.1.52
	once_cell@1.21.4
	proc-macro2@1.0.106
	quote@1.0.45
	r-efi@5.3.0
	regex-automata@0.4.14
	regex-syntax@0.8.11
	rustversion@1.0.22
	serde_core@1.0.228
	serde_derive@1.0.228
	shlex@2.0.1
	smol_strc@0.3.6
	syn@2.0.118
	tiny-keccak@2.0.2
	unicode-ident@1.0.24
	unicode-width@0.2.2
	version_check@0.9.5
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.4+wasi-0.2.12
	wasm-bindgen-macro-support@0.2.125
	wasm-bindgen-macro@0.2.125
	wasm-bindgen-shared@0.2.125
	wasm-bindgen@0.2.125
	windows-link@0.2.1
	wit-bindgen@0.57.1
	yansi@1.0.1
	zerocopy-derive@0.8.52
	zerocopy@0.8.52
	zmij@1.0.21
"

inherit cargo

DESCRIPTION="Fast statically-typed interpreted language with Rust-like syntax"
PATCHES=(
	"${FILESDIR}"/${P}-no-new-range-api.patch
)
HOMEPAGE="https://keel-lang.com https://github.com/horacehoff/keel"
SRC_URI="
	https://github.com/horacehoff/keel/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="Apache-2.0 CC0-1.0 ISC MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

DEPEND="dev-libs/libffi:="
RDEPEND="${DEPEND}"

src_prepare() {
	default
}

src_install() {
	cargo_src_install
	dodoc "${S}/README.md"
}
