# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.3

EAPI=8

CRATES="
	aho-corasick@1.1.4
	ariadne@0.6.0
	borsh@1.8.0
	bumpalo@3.20.3
	bytes@1.12.1
	cc@1.4.0
	cfg-if@1.0.4
	cfg_aliases@0.2.2
	find-msvc-tools@0.1.9
	fnv@1.0.7
	getrandom@0.3.4
	js-sys@0.3.103
	lexical-core@1.0.6
	lexical-parse-float@1.0.6
	lexical-parse-integer@1.0.6
	lexical-util@1.0.7
	lexical-write-integer@1.0.6
	libc@0.2.189
	libffi-sys@4.2.0
	libffi@5.1.1
	libloading@0.9.0
	libmimalloc-sys@0.1.49
	logos-codegen@0.16.1
	logos-derive@0.16.1
	logos@0.16.1
	memchr@2.8.3
	mimalloc@0.1.52
	once_cell@1.21.4
	proc-macro2@1.0.107
	quote@1.0.47
	r-efi@5.3.0
	regex-automata@0.4.16
	regex-syntax@0.8.11
	rustc-hash@2.1.3
	rustversion@1.0.23
	serde_core@1.0.229
	serde_derive@1.0.229
	shlex@2.0.1
	smol_strc@0.3.6
	syn@2.0.119
	syn@3.0.3
	unicode-ident@1.0.24
	unicode-width@0.2.2
	wasip2@1.0.4+wasi-0.2.12
	wasm-bindgen-macro-support@0.2.126
	wasm-bindgen-macro@0.2.126
	wasm-bindgen-shared@0.2.126
	wasm-bindgen@0.2.126
	windows-link@0.2.1
	wit-bindgen@0.57.1
	yansi@1.0.1
	zmij@1.0.23
"

inherit cargo

DESCRIPTION="Fast statically-typed interpreted language with Rust-like syntax"
HOMEPAGE="https://keel-lang.com https://github.com/horacehoff/keel"
SRC_URI="
	https://github.com/horacehoff/keel/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="Apache-2.0 ISC MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

IUSE="embed"

src_compile() {
	local myfeatures=()
	use embed && myfeatures+=(embed)
	cargo_src_compile --features "${myfeatures[*]}"
}

src_install() {
	cargo_src_install
	dodoc "${S}/README.md"
}
