#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${REDIS_SENTINEL_DIR:=/tmp}
: ${REDIS_SENTINEL_CONF:=/etc/keydb-sentinel.conf}
: ${REDIS_SENTINEL_USER:=keydb}
: ${REDIS_SENTINEL_GROUP:=keydb}
: ${REDIS_SENTINEL_TIMEOUT:=30}

command="/usr/sbin/keydb-sentinel"
command_args="${REDIS_SENTINEL_CONF}"
command_background="true"
command_user="${REDIS_SENTINEL_USER}:${REDIS_SENTINEL_GROUP}"
pidfile="/run/${RC_SVCNAME}.pid"
retry="${REDIS_SENTINEL_TIMEOUT}"
start_stop_daemon_args="--chdir \"${REDIS_SENTINEL_DIR}\""

depend() {
	use localmount logger
	after keepalived keydb
}
