# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="django-pagination"
HOMEPAGE="http://django-pagination.googlecode.com/"
SRC_URI="http://django-pagination.googlecode.com/files/${P}.tar.gz"
LICENSE="BSD"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND="dev-python/setuptools"

src_test() {
	PYTHONPATH=. "${python}" setup.py test || die "tests failed"
}

