.\"     Title: sunrise\-commit
.\"    Author: Alex Tarkovsky <alextarkovsky@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: November 5, 2006
.\"    Manual: overlay\-utils
.\"    Source: sunrise\-commit 0.2
.\"
.TH "SUNRISE\-COMMIT" "1" "November 5, 2006" "sunrise\-commit 0.2" "overlay\-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sunrise\-commit \- automates the Gentoo Sunrise Overlay commit process
.SH "SYNOPSIS"
.HP 15
\fBsunrise\-commit\fR [[\-\-changelog] | [\-c]] [[\-\-help] | [\-h]] [[\-\-noformat] | [\-m]] [[\-\-norepoman] | [\-p]] [[\-\-noupdate] | [\-d]] [[\-\-quiet] | [\-q]] [[\-\-verbose] | [\-v]] {\fImessage\fR}
.SH "DESCRIPTION"
.PP
The
\fBsunrise\-commit\fR
tool automates most of the process of committing changes to the Gentoo Sunrise Overlay. It currently aims to cover the most common scenarios.
.SH "OPTIONS"
.PP
\fB\-\-changelog\fR, \fB\-c\fR
.RS 3n
Create a
\fIChangeLog\fR
entry using
\fB\fImessage\fR\fR. This feature requires the environment variable
\fIECHANGELOG_USER\fR
to be set. To set this variable, do:
.sp
.RS 3n
.nf
$ \fBexport ECHANGELOG_USER="Your Name <your@mail.org>"\fR
  
.fi
.RE
You can make the value of
\fIECHANGELOG_USER\fR
persist between shell sessions by adding that line to your
\fI~/.bashrc\fR
file. Only one
\fIChangeLog\fR
entry should be made per commit, so if you have already modified your
\fIChangeLog\fR
locally since your last commit
\fBsunrise\-commit\fR
will exit with an error. If this happens, to keep the pre\-existing
\fIChangeLog\fR
modifications you can run
\fBsunrise\-commit\fR
again without
\fB\-\-changelog\fR, or to discard the pre\-existing modifications you should do the following before running
\fBsunrise\-commit\fR
again:
.sp
.RS 3n
.nf
$ \fBsvn revert ChangeLog\fR
.fi
.RE
.RE
.PP
\fB\-\-help\fR, \fB\-h\fR
.RS 3n
Show help.
.RE
.PP
\fB\-\-noformat\fR, \fB\-m\fR
.RS 3n
Disable automatic formatting of
\fB\fImessage\fR\fR. By default your message will be prefixed with
\fB"\fR\fB\fIcategoryname\fR\fR\fB/\fR\fB\fIpackagename\fR\fR\fB: "\fR
if you're committing from a directory containing one or more
\fI.ebuild\fR
files, otherwise the prefix will be
\fB"\fR\fB\fIcurrentdir\fR\fR\fB/\fR\fB\fIfirstchangedfile\fR\fR\fB: "\fR. If the default behavior produces an incorrect or undesired message prefix, set this option and supply your own prefix.
.RE
.PP
\fB\-\-norepoman\fR, \fB\-p\fR
.RS 3n
Skip repoman check.
.RE
.PP
\fB\-\-noupdate\fR, \fB\-d\fR
.RS 3n
Don't update from repository before committing.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 3n
Don't ask for confirmation. The default behavior is to prompt before finalizing commits.
.RE
.PP
\fB\-\-verbose\fR, \fB\-v\fR
.RS 3n
Show detailed information during commit.
.RE
.SS "message"
.PP
This should be a brief message describing your changes. It will be used as the Subversion commit message, and, if
\fB\-\-changelog\fR
is specified, it will also serve as the
\fIChangeLog\fR
entry.
.PP
When not using
\fB\-\-noformat\fR, please manually prefix your message with the package or file you're changing. When committing from a directory containing one or more
\fI.ebuild\fR
files the prefix convention is:
.sp
.RS 3n
.nf
"\fIcategoryname\fR/\fIpackagename\fR: "
.fi
.RE
.PP
For example:
.sp
.RS 3n
.nf
"app\-misc/youtranslate: "
.fi
.RE
.PP
A less common scenario is committing from non\-ebuild directories, in which case the prefix convention is:
.sp
.RS 3n
.nf
"\fIcurrentdir\fR/\fIchangedfile\fR: "
.fi
.RE
.PP
For multiple files in the same directory:
.sp
.RS 3n
.nf
"\fIcurrentdir\fR/ (\fIchangedfile1\fR \fIchangedfile2\fR \fIchangedfile3\fR): "
.fi
.RE
.PP
It's essential to terminate the prefix portion of your message with a colon character (":"). For readability you are encouraged to insert a space after the colon.
.PP
It's good practice to enclose the message in double quotation marks. Beware when using shell metacharacters in the message; the shell will evaluate these and likely produce unexpected behavior, so you must escape them:
.sp
.RS 3n
.nf
$ \fBsunrise\-commit \-c "A message with \\`ls\\` shouldn't be executed by \\
    the shell"\fR
.fi
.RE
.PP
Please practice common courtesy and include in your message the names (and email addresses if available/appropriate) of anyone else who contributed to the changes you're committing:
.sp
.RS 3n
.nf
$ \fBsunrise\-commit \-c "New ebuild for bug 1337. Thanks to Frank N. \\
    Furter, Hugo Furst <sheesh@thisnameisridiculous.com>, and \\
    null@void.net."\fR
.fi
.RE
.\" end of SS subsection "message"
.SH "OPERATIONS PERFORMED"
.PP

\fBsunrise\-commit\fR
will perform the following operations on the current working directory in the order listed.
.SS "svn update"
.PP

\fBsvn update\fR
is run to update your working copy with the latest changes from the trunk in the repository. If any conflicts between the updates and your local changes are detected,
\fBsunrise\-commit\fR
exits with an error message informing you of the files with conflicts and the names of their most recent committers so that you may contact these people to resolve the issue before committing your changes.
.\" end of SS subsection "svn update"
.SS "metadata.xml"
.PP
If the current directory contains one or more ebuilds and no
\fImetadata.xml\fR
is found, a skeleton
\fImetadata.xml\fR
is created.
.\" end of SS subsection "metadata.xml"
.SS "echangelog"
.PP
If
\fB\-\-changelog\fR
is specified, an entry is added to
\fIChangeLog\fR
in the current directory (and if that file doesn't exist it will be created for you first). The Gentoo
\fBechangelog\fR
utility is currently called to handle this operation.
.\" end of SS subsection "echangelog"
.SS "ebuild digest"
.PP
If the current directory contains one or more ebuilds then
\fBebuild \fR\fB\fIfilename\fR\fR\fB digest\fR
is run on each ebuild to create or update digest files and
\fIManifest\fR.
.\" end of SS subsection "ebuild digest"
.SS "svn add"
.PP

\fBsvn add\fR
is run to add all changes from the current directory in your working copy to Subversion locally.
.\" end of SS subsection "svn add"
.SS "repoman"
.PP

\fBrepoman\fR
is run.
\fBsunrise\-commit\fR
exits here if repoman finds errors, but it doesn't exit for warnings. Since the default
\fBsunrise\-commit\fR
behavior is to prompt you before finally performing a commit, you are given a chance to abort the commit if you see
\fBrepoman\fR
warnings regarding issues which require correction.
.\" end of SS subsection "repoman"
.SS "svn commit"
.PP
If no changes are found at this step
\fBsunrise\-commit\fR
exits with an error. Otherwise you are informed of the changes to be committed and of the exact commit message to be used. Unless
\fB\-\-quiet\fR
was specified, you are prompted for confirmation to proceed with the actual
\fBsvn commit\fR
operation.
.\" end of SS subsection "svn commit"
.SH "EXAMPLES"
.PP
Committing a new ebuild:
.sp
.RS 3n
.nf
$ \fBsunrise\-commit \-c "New ebuild for bug 1337. Thanks to Frank N. \\
    Furter, Hugo Furst <sheesh@thisnameisridiculous.com>, and \\
    null@void.net."\fR
.fi
.RE
.PP
Revising an existing ebuild:
.sp
.RS 3n
.nf
$ \fBsunrise\-commit \-v \-c "Adding upstream patch for buffer overflow."\fR
.fi
.RE
.PP
Committing changes from a non\-ebuild directory:
.sp
.RS 3n
.nf
$ \fBsunrise\-commit \-v \-m "scripts/dev/orderpizza.sh: Initial commit."\fR
.fi
.RE
.SH "AUTHORS"
.PP
\fBAlex\fR \fBTarkovsky\fR <alextarkovsky@gmail.com>
.sp -1n
.IP "" 3n
Author.
.PP
\fBStefan\fR \fBSchweizer\fR <genstef@gentoo.com>
.sp -1n
.IP "" 3n
Author.
