# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI="4"

inherit distutils elisp-common

SUPPORT_PYTHON_ABIS="1"
PYTHON_DEPEND="2"
RESTRICT_PYTHON_ABIS="3.*"

DESCRIPTION="An autocompletion library for Python"
HOMEPAGE="http://code.google.com/p/pysmell"
SRC_URI="mirror://pypi/p/${PN}/${P}.zip"
LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE="emacs vim"
RDEPEND="emacs? (
			app-emacs/pymacs
			virtual/emacs )"
DEPEND="${RDEPEND}
	app-arch/unzip"

SITEFILE=50${PN}-gentoo.el

src_compile() {
	distutils_src_compile
	if use emacs; then
		elisp-compile pysmell.el || die
	fi
}

src_install() {
	distutils_src_install
	if use emacs; then
		elisp-install ${PN} pysmell.el pysmell.elc || die
		elisp-site-file-install "${FILESDIR}/${SITEFILE}" || die
	fi
}

pkg_postinst() {
	use emacs && elisp-site-regen
}

pkg_postrm() {
	use emacs && elisp-site-regen
}
