# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit cmake

MY_JSON_VER="3.12.0"

DESCRIPTION="GPU-driven communication stack for scalable AI applications"
HOMEPAGE="https://microsoft.github.io/mscclpp/ https://github.com/microsoft/mscclpp"
SRC_URI="
	https://github.com/microsoft/mscclpp/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/nlohmann/json/archive/v${MY_JSON_VER}.tar.gz
		-> nlohmann_json-${MY_JSON_VER}.tar.gz
"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+cuda infiniband rocm static-libs test"
REQUIRED_USE="^^ ( cuda rocm )"
RESTRICT="!test? ( test )"

DEPEND="
	cuda? ( dev-util/nvidia-cuda-toolkit:= )
	rocm? ( dev-util/hip:= )
	sys-cluster/rdma-core
	sys-process/numactl
	test? ( virtual/mpi )
"
# rdma-core is loaded at runtime via dlopen; only needed in RDEPEND when IB is enabled
RDEPEND="
	cuda? ( dev-util/nvidia-cuda-toolkit:= )
	infiniband? ( sys-cluster/rdma-core )
	rocm? ( dev-util/hip:= )
	sys-process/numactl
"

src_prepare() {
	# Use the correct multilib libdir instead of the hardcoded 'lib'
	local libdir=$(get_libdir)
	find "${S}" -name "CMakeLists.txt" -exec sed -i \
		's|${INSTALL_PREFIX}/lib|'"${libdir}"'|g' {} + || die
	cmake_src_prepare
}

src_install() {
	cmake_src_install
	use static-libs || find "${ED}" -name "*.a" -delete || die

	# Upstream provides no CMake package config; generate one so consumers can
	# use find_package(mscclpp CONFIG REQUIRED) without vendoring the source.
	local libdir=$(get_libdir)
	local cmakedir="${ED}/usr/${libdir}/cmake/mscclpp"
	mkdir -p "${cmakedir}" || die

	# mscclppConfig.cmake — prefix is resolved relative to this file's location:
	#   /usr/<libdir>/cmake/mscclpp/  →  ../../../  →  /usr
	cat > "${cmakedir}/mscclppConfig.cmake" <<-EOF || die
		# mscclppConfig.cmake — generated by Gentoo dev-libs/mscclpp ebuild
		cmake_minimum_required(VERSION 3.16)
		if(TARGET mscclpp::mscclpp)
		  return()
		endif()
		get_filename_component(_mscclpp_prefix "\${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
		add_library(mscclpp::mscclpp SHARED IMPORTED)
		set_target_properties(mscclpp::mscclpp PROPERTIES
		  IMPORTED_SONAME  "libmscclpp.so.0"
		  IMPORTED_LOCATION "\${_mscclpp_prefix}/${libdir}/libmscclpp.so"
		  INTERFACE_INCLUDE_DIRECTORIES "\${_mscclpp_prefix}/include"
		)
		unset(_mscclpp_prefix)
	EOF

	cat > "${cmakedir}/mscclppConfigVersion.cmake" <<-EOF || die
		# mscclppConfigVersion.cmake — generated by Gentoo dev-libs/mscclpp ebuild
		set(PACKAGE_VERSION "${PV}")
		if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
		  set(PACKAGE_VERSION_COMPATIBLE FALSE)
		else()
		  set(PACKAGE_VERSION_COMPATIBLE TRUE)
		  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
		    set(PACKAGE_VERSION_EXACT TRUE)
		  endif()
		endif()
	EOF
}

src_configure() {
	local mycmakeargs=(
		# Bypass GPU detection at configure time (hardware may not be present in buildroot)
		-DMSCCLPP_BYPASS_GPU_CHECK=ON
		-DMSCCLPP_USE_CUDA=$(usex cuda)
		-DMSCCLPP_USE_ROCM=$(usex rocm)
		-DMSCCLPP_USE_IB=$(usex infiniband)
		-DMSCCLPP_BUILD_TESTS=$(usex test)
		# Python bindings belong in a separate dev-python/mscclpp-python ebuild
		-DMSCCLPP_BUILD_PYTHON_BINDINGS=OFF
		# Supply nlohmann/json source so FetchContent works offline
		-DFETCHCONTENT_FULLY_DISCONNECTED=ON
		-DFETCHCONTENT_SOURCE_DIR_JSON="${WORKDIR}/json-${MY_JSON_VER}"
	)
	cmake_src_configure
}
