# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# CRATES list is generated by pycargoebuild from Cargo.lock — never write by hand
CRATES="
	aho-corasick@1.1.4
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.104
	arc-swap@1.9.2
	async-trait@0.1.91
	atomic-waker@1.1.2
	autocfg@1.5.1
	aws-lc-rs@1.17.3
	aws-lc-sys@0.43.0
	axum-core@0.4.5
	axum-server@0.8.0
	axum@0.7.9
	base64@0.23.0
	bit-set@0.8.0
	bit-vec@0.8.0
	bitflags@2.13.1
	block2@0.6.2
	byteorder@1.5.0
	bytes@1.12.1
	cc@1.4.0
	cfg-if@1.0.4
	clap@4.4.18
	clap_builder@4.4.18
	clap_derive@4.4.7
	clap_lex@0.6.0
	cmake@0.1.58
	colorchoice@1.0.5
	crossbeam-deque@0.8.7
	crossbeam-epoch@0.9.20
	crossbeam-utils@0.8.22
	crunchy@0.2.4
	cudarc@0.11.9
	dispatch2@0.3.1
	dunce@1.0.5
	either@1.17.0
	equivalent@1.0.2
	errno@0.3.14
	fancy-regex@0.18.0
	find-msvc-tools@0.1.9
	fnv@1.0.7
	form_urlencoded@1.2.2
	fs-err@3.3.1
	fs_extra@1.3.0
	futures-channel@0.3.33
	futures-core@0.3.33
	futures-macro@0.3.31
	futures-sink@0.3.33
	futures-task@0.3.33
	futures-util@0.3.31
	getrandom@0.2.17
	getrandom@0.4.3
	h2@0.4.15
	half@2.4.1
	hashbrown@0.17.1
	heck@0.4.1
	http-body-util@0.1.4
	http-body@1.1.0
	http@1.4.2
	httparse@1.10.1
	httpdate@1.0.3
	hyper-util@0.1.20
	hyper@1.11.0
	indexmap@2.14.0
	is_terminal_polyfill@1.70.2
	itoa@1.0.18
	jobserver@0.1.35
	lazy_static@1.5.0
	libc@0.2.189
	libloading@0.8.9
	log@0.4.33
	matchers@0.2.0
	matchit@0.7.3
	memchr@2.8.3
	memmap2@0.9.11
	mime@0.3.17
	mio@1.2.2
	nu-ansi-term@0.50.3
	objc2-core-foundation@0.3.2
	objc2-encode@4.1.0
	objc2-foundation@0.3.2
	objc2-metal@0.3.2
	objc2@0.6.4
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	percent-encoding@2.3.2
	pin-project-lite@0.2.17
	pin-utils@0.1.0
	pkg-config@0.3.33
	proc-macro2@1.0.107
	quote@1.0.47
	r-efi@6.0.0
	rayon-core@1.12.1
	rayon@1.10.0
	regex-automata@0.4.16
	regex-syntax@0.8.11
	regex@1.13.1
	ring@0.17.14
	rustls-pki-types@1.15.1
	rustls-webpki@0.103.13
	rustls@0.23.43
	rustversion@1.0.23
	ryu@1.0.23
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_json@1.0.151
	serde_path_to_error@0.1.20
	serde_urlencoded@0.7.1
	sharded-slab@0.1.7
	shlex@2.0.1
	signal-hook-registry@1.4.8
	slab@0.4.12
	smallvec@1.15.2
	socket2@0.6.5
	strsim@0.10.0
	subtle@2.6.1
	syn@2.0.119
	syn@3.0.3
	sync_wrapper@1.0.2
	thiserror-impl@1.0.69
	thiserror@1.0.69
	thread_local@1.1.10
	tokio-macros@2.7.1
	tokio-rustls@0.26.4
	tokio-util@0.7.19
	tokio@1.53.1
	tower-http@0.7.0
	tower-layer@0.3.3
	tower-service@0.3.3
	tower@0.5.3
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-log@0.2.0
	tracing-subscriber@0.3.23
	tracing@0.1.44
	unicode-ident@1.0.24
	untrusted@0.9.0
	utf8parse@0.2.2
	valuable@0.1.1
	wasi@0.11.1+wasi-snapshot-preview1
	windows-link@0.2.1
	windows-sys@0.52.0
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	zeroize@1.9.0
	zmij@1.0.23
"

inherit cargo

DESCRIPTION="Pure-Rust GGUF inference engine with quantized CPU, Metal and CUDA kernels"
HOMEPAGE="https://github.com/antonellof/ferrox"
SRC_URI="
	https://github.com/antonellof/ferrox/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="Apache-2.0 BSD ISC MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
IUSE="cuda"

RDEPEND="cuda? ( dev-util/nvidia-cuda-toolkit )"

src_configure() {
	local myfeatures=( $(usev cuda) )
	cargo_src_configure
}

src_install() {
	cargo_src_install --path ./crates/ferrox-cli
	cargo_src_install --path ./crates/ferrox-server

	dodoc README.md
}
