# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.2

EAPI=8

CRATES="
	adler32@1.2.0
	aho-corasick@1.0.2
	android-tzdata@0.1.1
	android_system_properties@0.1.5
	ansi_term@0.12.1
	arc-swap@1.6.0
	async-channel@1.9.0
	async-executor@1.5.1
	async-global-executor@2.3.1
	async-io@1.13.0
	async-lock@2.7.0
	async-std@1.12.0
	async-task@4.4.0
	atomic-waker@1.1.1
	atty@0.2.14
	autocfg@1.1.0
	base64@0.13.1
	bitflags@1.3.2
	block-buffer@0.9.0
	blocking@1.3.1
	bumpalo@3.13.0
	bytecodec@0.4.15
	byteorder@1.4.3
	cc@1.0.81
	cfg-if@1.0.0
	chrono@0.4.26
	clap@2.34.0
	concurrent-queue@2.2.0
	core-foundation-sys@0.8.4
	cpufeatures@0.2.9
	crc32fast@1.3.2
	crossbeam-channel@0.5.8
	crossbeam-utils@0.8.16
	deranged@0.3.7
	digest@0.9.0
	dirs-next@2.0.0
	dirs-sys-next@0.1.2
	errno-dragonfly@0.1.2
	errno@0.3.2
	event-listener@2.5.3
	fastrand@1.9.0
	field-offset@0.3.6
	futures-channel@0.3.28
	futures-core@0.3.28
	futures-io@0.3.28
	futures-lite@1.13.0
	generic-array@0.14.7
	getrandom@0.2.10
	gloo-timers@0.2.6
	hermit-abi@0.1.19
	hermit-abi@0.3.2
	httpcodec@0.2.3
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.57
	instant@0.1.12
	io-lifetimes@1.0.11
	itoa@1.0.9
	js-sys@0.3.64
	kv-log-macro@1.0.7
	lazy_static@1.4.0
	libc@0.2.147
	libflate@1.4.0
	libflate_lz77@1.2.0
	linux-raw-sys@0.3.8
	log@0.4.19
	memchr@2.5.0
	memoffset@0.9.0
	num-traits@0.2.16
	num_threads@0.1.6
	once_cell@1.18.0
	opaque-debug@0.3.0
	parking@2.1.0
	pin-project-lite@0.2.11
	pin-utils@0.1.0
	polling@2.8.0
	proc-macro2@1.0.66
	quote@1.0.32
	redox_syscall@0.2.16
	redox_users@0.4.3
	regex-automata@0.3.6
	regex-syntax@0.7.4
	regex@1.9.3
	rle-decode-fast@1.0.3
	rustc_version@0.4.0
	rustix@0.37.23
	rustversion@1.0.14
	semver@1.0.18
	serde@1.0.182
	serde_derive@1.0.182
	sha-1@0.9.8
	slab@0.4.8
	slog-async@2.7.0
	slog-kvfilter@0.7.0
	slog-scope@4.4.0
	slog-stdlog@4.1.1
	slog-term@2.9.0
	slog@2.7.0
	sloggers@2.1.1
	socket2@0.4.9
	strsim@0.8.0
	syn@1.0.109
	syn@2.0.28
	take_mut@0.2.2
	term@0.7.0
	textwrap@0.11.0
	thiserror-impl@1.0.44
	thiserror@1.0.44
	thread_local@1.1.7
	time-core@0.1.1
	time-macros@0.2.11
	time@0.1.45
	time@0.3.25
	trackable@0.2.24
	trackable@1.3.0
	trackable_derive@1.0.0
	typenum@1.16.0
	unicode-ident@1.0.11
	unicode-width@0.1.10
	value-bag@1.4.1
	vec_map@0.8.2
	version_check@0.9.4
	waker-fn@1.1.0
	wasi@0.10.0+wasi-snapshot-preview1
	wasi@0.11.0+wasi-snapshot-preview1
	wasm-bindgen-backend@0.2.87
	wasm-bindgen-futures@0.4.37
	wasm-bindgen-macro-support@0.2.87
	wasm-bindgen-macro@0.2.87
	wasm-bindgen-shared@0.2.87
	wasm-bindgen@0.2.87
	web-sys@0.3.64
	widestring@0.4.3
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-acl@0.3.0
	windows-sys@0.48.0
	windows-targets@0.48.1
	windows@0.48.0
	windows_aarch64_gnullvm@0.48.0
	windows_aarch64_msvc@0.48.0
	windows_i686_gnu@0.48.0
	windows_i686_msvc@0.48.0
	windows_x86_64_gnu@0.48.0
	windows_x86_64_gnullvm@0.48.0
	windows_x86_64_msvc@0.48.0
"

inherit cargo

DESCRIPTION="WebSocket to TCP proxy server"
HOMEPAGE="https://github.com/sile/wstcp"
SRC_URI="
	https://github.com/sile/wstcp/archive/refs/tags/${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT BSD Unicode-DFS-2016 ZLIB"
SLOT="0"
KEYWORDS="~amd64"

src_prepare() {
	eapply --directory="${ECARGO_HOME}/gentoo/time-0.3.25" \
		"${FILESDIR}/time-0.3.25-type-annotation.patch"
	default
}

src_install() {
	cargo_src_install
	dodoc README.md
}
