# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Set-Object-1.27

DESCRIPTION="Set of Objects (smalltalkish: IdentitySet)"
HOMEPAGE="http://search.cpan.org/search?query=Set-Object&mode=dist"
SRC_URI="mirror://cpan/authors/id/S/SA/SAMV/Set-Object-1.27.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

DEPEND="dev-lang/perl"
