#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2
# $Header: $

depend() {
	need net
	use dns logger postgresql mysql
}

start()	{
	ebegin "Starting Red5"
        cd /opt/red5
	su -s /bin/bash -c "/usr/bin/nohup /opt/red5/red5.sh &" ${RED5_USER}
	eend $?
}

stop ()	{
	ebegin "Stopping Red5"
        su -s /bin/bash -c "killall -q -u ${RED5_USER} java" ${RED5_USER}
	eend $?
}

