# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# NOTE: This file is generated by pycargoebuild and then manually completed.
# Run: pycargoebuild -o CATEGORY/PKGNAME/PKGNAME-VERSION.ebuild /path/to/cloned/repo
# Then fill in DESCRIPTION, HOMEPAGE, KEYWORDS, and any system library DEPEND.

EAPI=8

# CRATES list is generated by pycargoebuild from Cargo.lock — never write by hand
CRATES="
	crate-name@1.0.0
	another-crate@2.3.4
"

inherit cargo

DESCRIPTION=""
HOMEPAGE="https://github.com/OWNER/REPO/"
SRC_URI="
	https://github.com/OWNER/REPO/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

# LICENSE is computed by pycargoebuild from all crate licenses
# Typical result combines main crate + dependency licenses:
LICENSE="MIT Apache-2.0"
SLOT="0"
KEYWORDS="~amd64"

# Add system library deps for *-sys crates found in CRATES list.
# Common examples:
# DEPEND="
# 	dev-libs/openssl:=
# 	sys-libs/zlib:=
# 	dev-db/sqlite:=
# "
# RDEPEND="${DEPEND}"
BDEPEND="
	virtual/pkgconfig
"

# Optional: expose Cargo features as USE flags
# IUSE="feature1 feature2"

src_configure() {
	# Default: build with all default features
	cargo_src_configure
	# With custom features:
	# local myfeatures=( $(usex feature1 feature1 '') )
	# cargo_src_configure --no-default-features
}

src_install() {
	cargo_src_install
	# If binary name differs from PN:
	# cargo_src_install --example mybin

	# Documentation:
	# einstalldocs
}
