#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${DYNOMITE_DIR:=/var/lib/dynomite}
: ${DYNOMITE_CONF:=/etc/dynomite/dynomite.yml}
: ${DYNOMITE_OPTS:="-c ${DYNOMITE_CONF}"}

LOGPATH=/var/log/${RC_SVCNAME}

command="/usr/sbin/dynomite"
command_args="${DYNOMITE_OPTS} --daemonize -o ${LOGPATH}/${RC_SVCNAME}.log"
command_background="true"
command_user=${RC_SVCNAME}
pidfile="/run/${RC_SVCNAME}.pid"
start_stop_daemon_args="--chdir \"${DYNOMITE_DIR}\""

depend() {
	use localmount logger
	after keepalived
}

start_pre() {
	if [ ! -d "${LOGPATH}" ] ; then
		mkdir -p "${LOGPATH}"
		chown "${command_user}:${command_user}" "${LOGPATH}"
	fi
}
