# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# based on dev-lang/squeak/squeak-3.10.ebuild

# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

EAPI="2"

inherit multilib subversion

DESCRIPTION="Sugar specific branch of Squeak"
HOMEPAGE="http://squeakvm.org/svn/squeak/branches/olpc/"
LICENSE="MIT"

SLOT="0"
KEYWORDS="x86 amd64"

IUSE=""

AMD64_DEPEND="
	amd64? (
	    app-emulation/emul-linux-x86-xlibs
	    app-emulation/emul-linux-x86-soundlibs
	    app-emulation/emul-linux-x86-gtklibs
	)"

RDEPEND="media-libs/alsa-lib
    sys-apps/dbus
    media-libs/freetype
    >=media-libs/gstreamer-0.10
    x11-libs/libX11
    x11-libs/libXext
    x11-libs/libXrender
    x11-libs/libXt
    media-libs/libogg
    x11-libs/pango
    sys-libs/e2fsprogs-libs
	${AMD64_DEPEND}"
DEPEND="dev-util/subversion
    media-libs/alsa-lib
    sys-apps/dbus
    media-libs/freetype
    >=media-libs/gstreamer-0.10
    x11-libs/libX11
    x11-libs/libXext
    x11-libs/libXrender
    x11-libs/libXt
    media-libs/libogg
    x11-libs/pango
    dev-util/pkgconfig
    sys-libs/e2fsprogs-libs
	${AMD64_DEPEND}"

SRC_URI=
ESVN_REPO_URI='http://squeakvm.org/svn/squeak/branches/olpc'
ESVN_REVISION=1969

src_unpack() {
	subversion_src_unpack
}

src_prepare() {
	epatch ${FILESDIR}/0.87/sugar-squeak-exclude-plugins.patch
	epatch ${FILESDIR}/0.87/sugar-squeak-makefile.patch
	epatch ${FILESDIR}/0.87/sugar-squeak-dprintf.patch
}

src_configure() {
	if use amd64; then
		multilib_toolchain_setup x86

		# prepare right libtool
		cp -r ${S} ${S}.tmp || die
		cd ${S}.tmp/platforms/unix/config
		aclocal || die
		libtoolize -c -f || die
		autoconf || die
		cd ${S}.tmp
		./autogen.sh || die
		cd ${S}
	fi

	sh autogen.sh --prefix=/usr --disable-rpath --without-rfb --without-npsqueak --without-quartz --without-gl || die

	if use amd64; then
		cp ${S}.tmp/bld/libtool ${S}/bld
		sed -i '/^PLUGINS_LA/s/GStreamerPlugin${la}//' ${S}/bld/Makefile
		sed -i '/^\t$(LINK) *$(squeak)/s/vm.vm.a//' ${S}/bld/Makefile
		sed -i '/^\t$(LINK) *$(squeak)/s/$(SQLIBS)/vm\/vm.a $(SQLIBS)/' ${S}/bld/Makefile
	fi
}

src_compile() {
	emake || die
}

src_install() {
	emake ROOT=${D} install || die
	
}

