# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DISTUTILS_USE_PEP517=pdm-backend
PYTHON_COMPAT=( python3_{13..14} )

inherit distutils-r1

EGIT_COMMIT="6b3a93f881f774b4d9cafbc153456c3347003884"

DESCRIPTION="Parse partial JSON generated by LLM"
HOMEPAGE="
	https://pypi.org/project/partial-json-parser/
	https://github.com/promplate/partial-json-parser
"
SRC_URI="https://github.com/promplate/partial-json-parser/archive/${EGIT_COMMIT}.tar.gz -> ${P}.gh.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="
"
#BDEPEND="
#	test? (
#	)
#"

EPYTEST_PLUGINS=()
distutils_enable_tests pytest

S="${WORKDIR}"/${PN}-${EGIT_COMMIT}
