# NOTE: Do not edit, file was generated by sugar-base/jhconvert::sugar
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI="2"

inherit base

DESCRIPTION="A pygtk widget for embedding mozilla"
HOMEPAGE="http://sugarlabs.org/"
LICENSE="LGPL-2"

SLOT="0"
KEYWORDS="x86 amd64"

IUSE=""

RDEPEND="x11-libs/gtk+
    dev-python/pygobject
    dev-python/pygtk
    dev-lang/python[sqlite]
    >=net-libs/xulrunner-1.9[python]"
DEPEND="x11-libs/gtk+
    dev-python/pygobject
    dev-python/pygtk
    dev-lang/python[sqlite]
    >=net-libs/xulrunner-1.9[python]"

SRC_URI='http://download.sugarlabs.org/sources/sucrose/glucose/hulahop/hulahop-0.5.0.tar.bz2'
S=${WORKDIR}/hulahop-0.5.0

src_unpack() {
	elog "unpack"
	unpack ${A}
}

src_prepare() {
	elog "prepare"
	epatch ${FILESDIR}/0.85/sugar-hulahop-configure.patch
}

src_configure() {
	elog "configure"
	echo 'pref("general.useragent.vendor", "Sugar Labs");' >> data/prefs.js || die
	echo 'pref("general.useragent.vendorSub", "0.85");' >> data/prefs.js || die
	echo 'pref("general.useragent.vendorComment", "hulahop/0.5.0");' >> data/prefs.js || die
	libtoolize --copy --force || die
	autoreconf -ivf || die
	econf --disable-static || die
}

src_compile() {
	elog "compile"
	emake || die
}

src_install() {
	elog "install"
	emake DESTDIR=${D} install || die
	dodoc COPYING NEWS
}

